In [1]:
# Homework. Lesson 16
# 1. Convert List to 1D Array
import numpy as np

# Original list
list1 = [12.23, 13.32, 100, 36.32]
print("Original List:", list1)

# Convert to NumPy array
array1 = np.array(list1)
print(array1)


Original List: [12.23, 13.32, 100, 36.32]
[ 12.23  13.32 100.    36.32]


In [2]:
# 2. Create 3x3 Matrix (2?10)
import numpy as np

# Create values from 2 to 10
matrix = np.arange(2, 11).reshape(3, 3)

print(matrix)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
# 3. Null Vector (10) & Update Sixth Value
import numpy as np

# Create a null vector of size 10
vector = np.zeros(10)
print("Original Null Vector:", vector)

# Update the sixth value to 11
vector[5] = 11
print("Updated Vector:", vector)


Original Null Vector: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated Vector: [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [4]:
# 4. Array from 12 to 38
import numpy as np

# Create array from 12 to 37
array = np.arange(12, 38)

print(array)


[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [5]:
# 5. Convert Array to Float Type
import numpy as np

# Original array
arr = np.array([1, 2, 3, 4])
print("Original array:", arr)

# Convert to float
float_arr = arr.astype(float)
print("Array converted to float:", float_arr)


Original array: [1 2 3 4]
Array converted to float: [1. 2. 3. 4.]


In [6]:
# 6. Celsius to Fahrenheit Conversion
import numpy as np

# Sample array (Fahrenheit values)
fahrenheit = np.array([0, 12, 45.21, 34, 99.91, 32])
print("Values in Fahrenheit degrees:", fahrenheit)

# Convert Fahrenheit → Centigrade
centigrade = (fahrenheit - 32) * 5/9
print("Values in Centigrade degrees:", np.round(centigrade, 2))

# Convert back Centigrade → Fahrenheit
fahrenheit_converted = (centigrade * 9/5) + 32
print("Converted back to Fahrenheit:", np.round(fahrenheit_converted, 2))


Values in Fahrenheit degrees: [ 0.   12.   45.21 34.   99.91 32.  ]
Values in Centigrade degrees: [-17.78 -11.11   7.34   1.11  37.73   0.  ]
Converted back to Fahrenheit: [ 0.   12.   45.21 34.   99.91 32.  ]


In [7]:
# 7. Append Values to Array (Do self-tudy)
import numpy as np

# Original array
arr = np.array([10, 20, 30])
print("Original array:", arr)

# Append new values
new_arr = np.append(arr, [40, 50, 60, 70, 80, 90])
print("After append values to the end of the array:", new_arr)


Original array: [10 20 30]
After append values to the end of the array: [10 20 30 40 50 60 70 80 90]


In [8]:
# 8. Array Statistical Functions (Do self-tudy)
import numpy as np

# Create a random array of 10 elements
arr = np.random.randint(1, 100, 10)   # random integers from 1 to 99
print("Random Array:", arr)

# Mean
mean_val = np.mean(arr)
# Median
median_val = np.median(arr)
# Standard Deviation
std_val = np.std(arr)

print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_val)


Random Array: [32 63 38  6 93 25 30 74 50 33]
Mean: 44.4
Median: 35.5
Standard Deviation: 24.491631223746612


In [9]:
# 9 Find min and max
import numpy as np

# Create a 10x10 array with random values between 0 and 1
arr = np.random.rand(10, 10)
print("10x10 Random Array:\n", arr)

# Find minimum and maximum values
min_val = arr.min()
max_val = arr.max()

print("\nMinimum Value:", min_val)
print("Maximum Value:", max_val)


10x10 Random Array:
 [[0.95821051 0.68344604 0.68924912 0.96722255 0.33348421 0.91707307
  0.5266082  0.71147927 0.28071367 0.19288121]
 [0.70614003 0.96387531 0.91467089 0.8797824  0.09618937 0.59424679
  0.08742801 0.22593512 0.8865103  0.40771432]
 [0.10535469 0.12257168 0.42079076 0.09811973 0.54524609 0.0712242
  0.7662918  0.149486   0.00262321 0.86340876]
 [0.3161904  0.8866667  0.49586738 0.62657422 0.90677052 0.56360784
  0.09236353 0.64759344 0.72225656 0.37764363]
 [0.43806071 0.61377148 0.73932509 0.58631121 0.9280885  0.40229788
  0.59169468 0.81811923 0.95435736 0.0529934 ]
 [0.80283125 0.81027734 0.72921448 0.89568077 0.46187475 0.0392182
  0.39326279 0.78910581 0.4253824  0.69295761]
 [0.76775509 0.93433753 0.24427343 0.29502117 0.59862924 0.53750983
  0.85086155 0.62088461 0.4136806  0.3568333 ]
 [0.31336545 0.43158079 0.22997173 0.45013133 0.013782   0.04965574
  0.14186918 0.29514925 0.67667841 0.79141141]
 [0.53247538 0.50690573 0.22608977 0.43005794 0.11878911 0.97

In [10]:
# 10
import numpy as np

# Create a 3x3x3 array with random values between 0 and 1
arr = np.random.rand(3, 3, 3)

print("3x3x3 Random Array:\n", arr)


3x3x3 Random Array:
 [[[0.9246442  0.30313198 0.40340389]
  [0.91613673 0.873824   0.82267011]
  [0.5348144  0.93382392 0.20475473]]

 [[0.82202164 0.39110215 0.50209779]
  [0.66297363 0.3168438  0.0557412 ]
  [0.87287804 0.58702892 0.41846413]]

 [[0.40344942 0.57300217 0.81792541]
  [0.05313583 0.94602124 0.5884913 ]
  [0.34850989 0.75474336 0.58407736]]]
